using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NUnit.Framework;

namespace Kra.Test
{
    [TestFixture]
    public class ClassFormatterTest
    {
        [Test]
        public  void  FormatTest<>()
        {
            Assert.Fail("autogenerated");
        }

        [Test]
        public  void  GetTypeAccessorModifiersTest<>()
        {
            Assert.Fail("autogenerated");
        }

        [Test]
        public  void  GetTypeModifiersTest<>()
        {
            Assert.Fail("autogenerated");
        }

        [Test]
        public  void  GetTypeTest<>()
        {
            Assert.Fail("autogenerated");
        }
    }
}