using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NUnit.Framework;

namespace Kra.Test
{
    [TestFixture]
    public class ConstructorFormatterTest
    {
        [Test]
        public  void  FormatTest<>()
        {
            Assert.Fail("autogenerated");
        }

        [Test]
        public  void  GetNameTest<>()
        {
            Assert.Fail("autogenerated");
        }

        [Test]
        public  void  GetTypeAccessorModifiersTest<>()
        {
            Assert.Fail("autogenerated");
        }

        [Test]
        public  void  GetConstructArgumentsTest<>()
        {
            Assert.Fail("autogenerated");
        }

        [Test]
        public  void  GetGenericTypeTest<>()
        {
            Assert.Fail("autogenerated");
        }

        [Test]
        public  void  GetGenericArgumentsTypeTest<>()
        {
            Assert.Fail("autogenerated");
        }
    }
}