using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NUnit.Framework;
using AssemblyBrowserLib.format;

namespace AssemblyBrowserLib.format.Test
{

    [TestFixture]
    public class ConstructorFormatterTest
    {
        private ConstructorFormatter _ConstructorFormatter;    
        [Test]
        public void FormatTest()
        {
            ConstructorInfo constrInfo=null;

            _ConstructorFormatter.Format(constrInfo);
            Assert.Fail("autogenerated");
        }

    }
}