using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NUnit.Framework;

namespace Kra.Test.Test
{
[TestFixture]
    public class FieldFormatterTest
    {
        private FieldFormatter _FieldFormatter;    
        [Test]
        public void FormatTest()
        {
            FieldInfo fieldInfo=null;

            int actual=_FieldFormatter.Format(fieldInfo);            
            
            int expected = 0;
            Assert.That(actual, Is.EqualTo(expected));
            Assert.Fail("autogenerated");
        }
        
    }
}