using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NUnit.Framework;
using AssemblyBrowserLib.format;

namespace AssemblyBrowserLib.format.Test
{

    [TestFixture]
    public class FieldFormatterTest
    {
        private FieldFormatter _FieldFormatter;    
        [Test]
        public void FormatTest()
        {
            FieldInfo fieldInfo=null;

            _FieldFormatter.Format(fieldInfo);
            Assert.Fail("autogenerated");
        }

    }
}