using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NUnit.Framework;

namespace Kra.Test.Test
{
[TestFixture]
    public class MethodFormatterTest
    {
        private MethodFormatter _MethodFormatter;    
        [Test]
        public void FormatTest()
        {
            System.Reflection.MethodInfo methodInfo=null;

            int actual=_MethodFormatter.Format(methodInfo);            
            
            int expected = 0;
            Assert.That(actual, Is.EqualTo(expected));
            Assert.Fail("autogenerated");
        }
        
    }
}