using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NUnit.Framework;
using AssemblyBrowserLib.format;

namespace AssemblyBrowserLib.format.Test
{

    [TestFixture]
    public class MethodFormatterTest
    {
        private MethodFormatter _MethodFormatter;    
        [Test]
        public void FormatTest()
        {
            System.Reflection.MethodInfo methodInfo=null;

            _MethodFormatter.Format(methodInfo);
            Assert.Fail("autogenerated");
        }

    }
}