using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NUnit.Framework;
using AssemblyBrowserLib.format;

namespace AssemblyBrowserLib.format.Test
{

    [TestFixture]
    public class PropertiesFormatterTest
    {
        private PropertiesFormatter _PropertiesFormatter;    
        [Test]
        public void FormatTest()
        {
            PropertyInfo propertyInfo=null;

            _PropertiesFormatter.Format(propertyInfo);
            Assert.Fail("autogenerated");
        }

    }
}