using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NUnit.Framework;

namespace Kra.Test.Test
{
[TestFixture]
    public class PropertiesFormatterTest
    {
        private PropertiesFormatter _PropertiesFormatter;    
        [Test]
        public void FormatTest()
        {
            PropertyInfo propertyInfo=null;

            int actual=_PropertiesFormatter.Format(propertyInfo);            
            
            int expected = 0;
            Assert.That(actual, Is.EqualTo(expected));
            Assert.Fail("autogenerated");
        }
        
    }
}