using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NUnit.Framework;
using Moq;

namespace Kra.Test.Test
{

    [TestFixture]
    public class ClassFormatterTest
    {
        private ClassFormatter _ClassFormatter;    
        private Mock<IEnumerable<string> >_list;

        [SetUp]
        public void SetUp()
        {
            _list = new Mock<IEnumerable<string>>();
            _ClassFormatter = new ClassFormatter(_list.Object);
        }        

        [Test]
        public void Format1Test()
        {
            Type type1=null;
            int kra1=null;

            _ClassFormatter.Format1(type1, kra1);
            Assert.Fail("autogenerated");
        }

        [Test]
        public void FormatTest()
        {
            Type type=null;
            int kra=null;

            _ClassFormatter.Format(type, kra);
            Assert.Fail("autogenerated");
        }

    }
}