using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using AssemblyBrowserLib.format;
using NUnit.Framework;
using Moq;
using MyCode;

namespace Kra.Test.Test
{
[TestFixture]
    public class ClassFormatterTest
    {
        private ClassFormatter _ClassFormatter;    
        private Mock<IEnumerable<string> >_list;

        [SetUp]
        public void SetUp()
        {
            _list = new Mock<IEnumerable<string>>();
            _ClassFormatter = new ClassFormatter(_list.Object);
        }        

        [Test]
        public void FormatTest()
        {
            Type type=null;
            int kra=null;

            int actual=_ClassFormatter.Format(type, kra);            
            
            int expected = 0;
            Assert.That(actual, Is.EqualTo(expected));
            Assert.Fail("autogenerated");
        }
        
    }
}