using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NUnit.Framework;
using Moq;
using MyCode;

namespace Kra.Test
{

    [TestFixture]
    public class ClassFormatterTest
    {
        private ClassFormatter _ClassFormatter;    
        private Mock<IEnumerable<string> >_list;

        [SetUp]
        public void SetUp()
        {
            _list = new Mock<IEnumerable<string>>();
            _ClassFormatter = new ClassFormatter(_list.Object);
        }        

        [Test]
        public void Format1Test()
        {
            Type type1 = default;
            int kra1 = default;

            _ClassFormatter.Format1(type1, kra1);
            Assert.Fail("autogenerated");
        }

        [Test]
        public void FormatTest()
        {
            Type type = default;
            int kra = default;

            int actual=_ClassFormatter.Format(type, kra);            
            
            int expected = 0;
            Assert.That(actual, Is.EqualTo(expected));
            Assert.Fail("autogenerated");
        }

        [Test]
        public void GetTypeTest()
        {
            Type type = default;

            int actual=_ClassFormatter.GetType(type);            
            
            int expected = 0;
            Assert.That(actual, Is.EqualTo(expected));
            Assert.Fail("autogenerated");
        }

    }
}