using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NUnit.Framework;
using Moq;
using ClassFormatterN;

namespace ClassFormatterN.Test
{

    [TestFixture]
    public class ClassFormatterTest
    {
        private ClassFormatter _classFormatter;    
        private Mock<IEnumerable<string> >_list;

        [SetUp]
        public void SetUp()
        {
            _list = new Mock<IEnumerable<string>>();
            _classFormatter = new ClassFormatter(_list.Object);
        }        

        [Test]
        public void Format1Test()
        {
            Type type1 = default;
            int kra1 = default;

            ClassFormatter.Format1(type1, kra1);
            Assert.Fail("autogenerated");
        }

        [Test]
        public void FormatTest()
        {
            Type type = default;
            int kra = default;

            string actual=_classFormatter.Format(type, kra);

            string expected = default;
            Assert.That(actual, Is.EqualTo(expected));
            Assert.Fail("autogenerated");
        }

        [Test]
        public void GetTypeTest()
        {
            Type type = default;

            string actual=ClassFormatter.GetType(type);

            string expected = default;
            Assert.That(actual, Is.EqualTo(expected));
            Assert.Fail("autogenerated");
        }

    }
}