using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NUnit.Framework;
using AssemblyBrowserLib.format;

namespace AssemblyBrowserLib.format.Test
{

    [TestFixture]
    public class ConstructorFormatterTest
    {
        private ConstructorFormatter _ConstructorFormatter;    
        [Test]
        public void FormatTest()
        {
            ConstructorInfo constrInfo = default;

            int actual=_ConstructorFormatter.Format(constrInfo);            
            
            int expected = 0;
            Assert.That(actual, Is.EqualTo(expected));
            Assert.Fail("autogenerated");
        }

        [Test]
        public void GetNameTest()
        {
            ConstructorInfo constrInfo = default;

            int actual=_ConstructorFormatter.GetName(constrInfo);            
            
            int expected = 0;
            Assert.That(actual, Is.EqualTo(expected));
            Assert.Fail("autogenerated");
        }

        [Test]
        public void GetTypeAccessorModifiersTest()
        {
            ConstructorInfo constrInfo = default;

            int actual=_ConstructorFormatter.GetTypeAccessorModifiers(constrInfo);            
            
            int expected = 0;
            Assert.That(actual, Is.EqualTo(expected));
            Assert.Fail("autogenerated");
        }

        [Test]
        public void GetGenericArgumentsTypeTest()
        {
            IEnumerable<Type> arguments = default;

            int actual=_ConstructorFormatter.GetGenericArgumentsType(arguments);            
            
            int expected = 0;
            Assert.That(actual, Is.EqualTo(expected));
            Assert.Fail("autogenerated");
        }

    }
}