using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NUnit.Framework;
using AssemblyBrowserLib.format;

namespace AssemblyBrowserLib.format.Test
{

    [TestFixture]
    public class ConstructorFormatterTest
    {
        [Test]
        public void FormatTest()
        {
            ConstructorInfo constrInfo = default;

            string actual=ConstructorFormatter.Format(constrInfo);

            string expected = default;
            Assert.That(actual, Is.EqualTo(expected));
            Assert.Fail("autogenerated");
        }

        [Test]
        public void GetNameTest()
        {
            ConstructorInfo constrInfo = default;

            string actual=ConstructorFormatter.GetName(constrInfo);

            string expected = default;
            Assert.That(actual, Is.EqualTo(expected));
            Assert.Fail("autogenerated");
        }

        [Test]
        public void GetTypeAccessorModifiersTest()
        {
            ConstructorInfo constrInfo = default;

            string actual=ConstructorFormatter.GetTypeAccessorModifiers(constrInfo);

            string expected = default;
            Assert.That(actual, Is.EqualTo(expected));
            Assert.Fail("autogenerated");
        }

        [Test]
        public void GetGenericArgumentsTypeTest()
        {
            IEnumerable<Type> arguments = default;

            string actual=ConstructorFormatter.GetGenericArgumentsType(arguments);

            string expected = default;
            Assert.That(actual, Is.EqualTo(expected));
            Assert.Fail("autogenerated");
        }

    }
}