using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NUnit.Framework;
using AssemblyBrowserLib.format;

namespace AssemblyBrowserLib.format.Test
{

    [TestFixture]
    public class MethodFormatterTest
    {
        [Test]
        public void FormatTest()
        {
            System.Reflection.MethodInfo methodInfo = default;

            string actual=MethodFormatter.Format(methodInfo);

            string expected = default;
            Assert.That(actual, Is.EqualTo(expected));
            Assert.Fail("autogenerated");
        }

    }
}